import { Station, BRTCorridor, NBRTLine, CBRTLine, StationCode } from "@/types/index";

export const main_corridors: BRTCorridor[] = [
  {id: 1, color: "#d02127", stationIdsDir1: [], stationIdsDir2: []},
  {id: 2, color: "#294a99", stationIdsDir1: ["2-01", "2-02", "2-03", "2-04", "2-05", "2-06", "2-07", "2-08", "2-09", "2-10", "2-11", "2-12", "2-13", "2-14", "2-15", "2-16", "2-17", "2-18", "2-19", "1-14"], stationIdsDir2:["1-14", "2-22", "2-23", "2-24", "2-12", "2-11", "2-10", "2-09", "2-08", "2-07", "2-06", "2-05", "2-04", "2-03", "2-02", "2-01"]},
  {id: 3, color: "#fbc71f", stationIdsDir1: ["3-01", "3-02", "3-03", "3-04", "3-05", "3-06", "3-07", "3-08", "3-09", "3-10", "3-11", "3-12", "8-23", "1-14"], stationIdsDir2:["1-14", "8-23", "3-12", "3-11", "3-10", "3-09", "3-08", "3-07", "3-06", "3-05", "3-04", "3-03", "3-02", "3-01"]},
  {id: 4, color: "#502d5f", stationIdsDir1: [], stationIdsDir2: []},
  {id: 5, color: "#cc6128", stationIdsDir1: ["5-01", "5-02", "5-03", "5-04", "5-05", "5-06", "5-07", "5-08", "5-09", "5-10", "5-11", "5-12", "5-13", "5-14", "5-15", "5-16", "5-17", "5-18"], stationIdsDir2: ["5-18", "5-15", "5-14", "5-13", "5-12", "5-11", "5-10", "5-09", "5-08", "5-07", "5-06", "5-05", "5-04", "5-03", "5-02", "5-01"]},
  {id: 6, color: "#2ca74a", stationIdsDir1: [], stationIdsDir2:[]},
  {id: 7, color: "#e82860", stationIdsDir1: [], stationIdsDir2:[]},
  {id: 8, color: "#d73492", stationIdsDir1: [], stationIdsDir2:[]},
  {id: 9, color: "#43a09a", stationIdsDir1: [], stationIdsDir2: []}, 
  {id: 10, color: "#961f22", stationIdsDir1: [], stationIdsDir2: []},
  {id: 11, color: "#2e3192", stationIdsDir1: [], stationIdsDir2:[]},
  {id: 12, color: "#77bb79", stationIdsDir1: [], stationIdsDir2:[]},
  {id: 13, color: "#783378", stationIdsDir1: [], stationIdsDir2:[]},
  {id: 14, color: "#ed882e", stationIdsDir1: [], stationIdsDir2: []},
]

export const cbrt_lines: CBRTLine[] = [
  {id: "2A", color: "#50a6e4", stationIdsDir1: ["2-01", "2-02", "2-03", "2-04", "2-05", "2-06", "2-07", "2-08", "2-09", "2-10", "2-11", "2-12", "2-24", "2-22", "8-23", "3-12", "3-11", "3-10", "3-09", "3-08", "3-07", "3-06", "3-05", "3-04"], stationIdsDir2: ["3-04", "3-05", "3-06", "3-07", "3-08", "3-09", "3-10", "3-11", "3-12", "8-23", "2-22", "2-23", "2-24", "2-12", "2-11", "2-10", "2-09", "2-08", "2-07", "2-06", "2-05", "2-04", "2-03", "2-02", "2-01"]}, 
  {id: "3F", color: "#826a20", stationIdsDir1: [], stationIdsDir2: []},
  {id: "3H", color: "#e77721", stationIdsDir1: [], stationIdsDir2: []},
  {id: "4D", color: "#ed8fc1", stationIdsDir1: [], stationIdsDir2: []},
  {id: "5C", color: "#95d8c6", stationIdsDir1: ["7-07", "7-08", "7-09", "7-10", "7-11", "7-12", "7-13", "5-18", "5-15", "5-14", "5-13", "5-12", "5-11", "5-10", "5-09", "5-08", "2-24", "2-22", "1-14", "2-19", "2-18"], stationIdsDir2: ["2-18", "5-06", "5-08", "5-09", "5-10", "5-11", "5-12", "5-13", "5-14", "5-15", "5-16", "5-17", "5-18", "7-13", "7-12", "7-11", "7-10", "7-09", "7-08", "10-22", "7-07"]},
  {id: "6A", color: "#72c18b", stationIdsDir1: [], stationIdsDir2: []},
  {id: "6B", color: "#90b870", stationIdsDir1: [], stationIdsDir2: []},
  {id: "6V", color: "#3b907d", stationIdsDir1: [], stationIdsDir2: []},
  {id: "7F", color: "#fa2b75", stationIdsDir1: [], stationIdsDir2: []},
  {id: "9A", color: "#8fa03d", stationIdsDir1: [], stationIdsDir2: []},
  {id: "9C", color: "#39a26b", stationIdsDir1: [], stationIdsDir2: []},
  {id: "9N", color: "#783e40", stationIdsDir1: [], stationIdsDir2: []},
  {id: "10D", color: "#9d3237", stationIdsDir1: [], stationIdsDir2: []},
  {id: "10H", color: "#9c050c", stationIdsDir1: [], stationIdsDir2: []},
  {id: "13B", color: "#942087", stationIdsDir1: [], stationIdsDir2: []},
  {id: "13E", color: "#643683", stationIdsDir1: [], stationIdsDir2: []},
  {id: "L13E", color: "#643683", stationIdsDir1: [], stationIdsDir2: []},
]

export const stations: Station[] = [
  {
    id: "1-14",
    name: "Monumen Nasional",
    codes: [{ corridorId: 1, code: 14 }, { corridorId: 2, code: 21 }],
    brtCorridorIds: [1, 2, 3],
    cbrtLineIds: ["5C", "7F"],
    nbrtLineIds: [],
    doorside: "right",
  },
  {
    id: "2-01",
    name: "Pulo Gadung",
    codes: [{ corridorId: 2, code: 1 }, { corridorId: 4, code: 1 }],
    brtCorridorIds: [2, 4],
    cbrtLineIds: ["2A", "4D"],
    nbrtLineIds: [],
    doorside: "",
  },
  {
    id: "2-02",
    name: "Bermis",
    codes: [{ corridorId: 2, code: 2 }],
    brtCorridorIds: [2],
    cbrtLineIds: ["2A"],
    nbrtLineIds: [],
    doorside: "right",
  },
  {
    id: "2-03",
    name: "Pulo Mas",
    codes: [{ corridorId: 2, code: 3 }],
    brtCorridorIds: [2],
    cbrtLineIds: ["2A"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "2-04",
    name: "Perintis Kemerdekaan",
    codes: [{ corridorId: 2, code: 4 }],
    brtCorridorIds: [2],
    cbrtLineIds: ["2A"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "2-05",
    name: "Pedongkelan",
    codes: [{ corridorId: 2, code: 5 }],
    brtCorridorIds: [2],
    cbrtLineIds: ["2A"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "2-06",
    name: "Cempaka Mas",
    codes: [{ corridorId: 2, code: 6 }, { corridorId: 10, code: 8 }],
    brtCorridorIds: [2, 10],
    cbrtLineIds: ["2A", "7F", "10D"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "2-07",
    name: "Sumur Batu",
    codes: [{ corridorId: 2, code: 7 }],
    brtCorridorIds: [2],
    cbrtLineIds: ["2A", "7F"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "2-08",
    name: "Cempaka Baru",
    codes: [{ corridorId: 2, code: 8 }],
    brtCorridorIds: [2],
    cbrtLineIds: ["2A", "7F"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "2-09",
    name: "Pasar Cempaka Putih",
    codes: [{ corridorId: 2, code: 9 }],
    brtCorridorIds: [2],
    cbrtLineIds: ["2A", "7F"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "2-10",
    name: "Rawa Selatan",
    codes: [{ corridorId: 2, code: 10 }],
    brtCorridorIds: [2],
    cbrtLineIds: ["2A", "7F"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "2-11",
    name: "Galur",
    codes: [{ corridorId: 2, code: 11 }],
    brtCorridorIds: [2],
    cbrtLineIds: ["2A", "7F"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "2-12",
    name: "Senen TOYOTA Rangga",
    codes: [{ corridorId: 2, code: 12 }, { corridorId: 5, code: 7 }, { corridorId: 14, code: 1 }],
    brtCorridorIds: [2, 5, 14],
    cbrtLineIds: ["2A", "7F"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "2-13",
    name: "Senen Raya",
    codes: [{ corridorId: 2, code: 13 }, { corridorId: 14, code: 2 }],
    brtCorridorIds: [2, 14],
    cbrtLineIds: [],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "2-14",
    name: "RSPAD",
    codes: [{ corridorId: 2, code: 14 }],
    brtCorridorIds: [2],
    cbrtLineIds: [],
    nbrtLineIds: [], 
    doorside: "left",
  },
  {
    id: "2-15",
    name: "Pejambon",
    codes: [{ corridorId: 2, code: 15 }],
    brtCorridorIds: [2],
    cbrtLineIds: [],
    nbrtLineIds: [], 
    doorside: "left",
  },
  {
    id: "2-16",
    name: "Gambir",
    codes: [{ corridorId: 2, code: 16 }],
    brtCorridorIds: [2],
    cbrtLineIds: [],
    nbrtLineIds: [], 
    doorside: "left",
  },
  {
    id: "2-17",
    name: "Istiqlal",
    codes: [{ corridorId: 2, code: 17 }],
    brtCorridorIds: [2],
    cbrtLineIds: [],
    nbrtLineIds: [], 
    doorside: "left",
  },
  {
    id: "2-18",
    name: "Juanda",
    codes: [{ corridorId: 2, code: 18 }, { corridorId: 3, code: 15 }],
    brtCorridorIds: [2, 8],
    cbrtLineIds: ["5C", "7F", "10H"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "2-19",
    name: "Pecenongan",
    codes: [{ corridorId: 2, code: 19 }, { corridorId: 3, code: 14 }],
    brtCorridorIds: [2, 8],
    cbrtLineIds: ["5C", "7F", "10H"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "2-22",
    name: "Balai Kota",
    codes: [{ corridorId: 2, code: 22 }],
    brtCorridorIds: [2],
    cbrtLineIds: ["2A", "5C", "6A", "6B", "7F"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "2-23",
    name: "Gambir 2",
    codes: [{ corridorId: 2, code: 23 }],
    brtCorridorIds: [2],
    cbrtLineIds: ["2A"],
    nbrtLineIds: [],
    doorside: "left",
  },
  {
    id: "2-24",
    name: "Kwitang",
    codes: [{ corridorId: 2, code: 24 }],
    brtCorridorIds: [2],
    cbrtLineIds: ["2A", "5C", "7F"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "3-01",
    name: "Kalideres",
    codes: [{ corridorId: 3, code: 1 }],
    brtCorridorIds: [3],
    cbrtLineIds: ["3F"],
    nbrtLineIds: [],
    doorside: "",
  },
  {
    id: "3-02",
    name: "Pesakih",
    codes: [{ corridorId: 3, code: 2 }],
    brtCorridorIds: [3],
    cbrtLineIds: ["3F"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "3-03",
    name: "Sumur Bor",
    codes: [{ corridorId: 3, code: 3 }],
    brtCorridorIds: [3],
    cbrtLineIds: ["3F"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "3-04",
    name: "Rawa Buaya",
    codes: [{ corridorId: 3, code: 4 }],
    brtCorridorIds: [3],
    cbrtLineIds: ["2A", "3F"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "3-05",
    name: "Jembatan Baru",
    codes: [{ corridorId: 3, code: 5 }],
    brtCorridorIds: [3],
    cbrtLineIds: ["2A", "3F"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "3-06",
    name: "Pulo Nangka",
    codes: [{ corridorId: 3, code: 6 }],
    brtCorridorIds: [3],
    cbrtLineIds: ["2A", "3F"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "3-07",
    name: "Jembatan Gantung",
    codes: [{ corridorId: 3, code: 7 }],
    brtCorridorIds: [3],
    cbrtLineIds: ["2A", "3F"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "3-08",
    name: "Taman Kota",
    codes: [{ corridorId: 3, code: 8 }],
    brtCorridorIds: [3],
    cbrtLineIds: ["2A", "3F"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "3-09",
    name: "Damai",
    codes: [{ corridorId: 3, code: 9 }, { corridorId: 8, code: 17}],
    brtCorridorIds: [3, 8],
    cbrtLineIds: ["2A", "3F", "3H"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "3-10",
    name: "Jelambar",
    codes: [{ corridorId: 3, code: 10 }, { corridorId: 8, code: 18}],
    brtCorridorIds: [3, 8],
    cbrtLineIds: ["2A", "3F", "3H"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "3-11",
    name: "Grogol",
    codes: [{ corridorId: 3, code: 11 }, { corridorId: 8, code: 19 }, { corridorId: 9, code: 20 }],
    brtCorridorIds: [3, 8, 9],
    cbrtLineIds: ["2A", "3F", "3H", "9A"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "3-12",
    name: "Roxy",
    codes: [{ corridorId: 3, code: 12 }],
    brtCorridorIds: [3],
    cbrtLineIds: ["2A", "3H"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "5-01", 
    name: "Ancol",
    codes: [{ corridorId: 5, code: 1 }],
    brtCorridorIds: [5],
    cbrtLineIds: [],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "5-02", 
    name: "Pademangan",
    codes: [{ corridorId: 5, code: 2 }],
    brtCorridorIds: [5],
    cbrtLineIds: ["10H"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "5-03", 
    name: "Gunung Sahari",
    codes: [{ corridorId: 5, code: 3 }, { corridorId: 12, code: 9 }],
    brtCorridorIds: [5, 12],
    cbrtLineIds: ["10H"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "5-04", 
    name: "Jembatan Merah",
    codes: [{ corridorId: 5, code: 4 }, { corridorId: 12, code: 10 }],
    brtCorridorIds: [5, 12],
    cbrtLineIds: ["10H"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "5-05", 
    name: "Pasar Baru Timur",
    codes: [{ corridorId: 5, code: 5 }],
    brtCorridorIds: [5],
    cbrtLineIds: ["10H"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "5-06", 
    name: "Lapangan Banteng",
    codes: [{ corridorId: 5, code: 6 }],
    brtCorridorIds: [5],
    cbrtLineIds: ["5C"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "5-07", 
    name: "Jaga Jakarta",
    codes: [{ corridorId: 2, code: 12 }, { corridorId: 5, code: 7 }, { corridorId: 14, code: 1 }],
    brtCorridorIds: [2, 5, 14],
    cbrtLineIds: ["2A", "7F"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "5-08", 
    name: "Pal Putih",
    codes: [{ corridorId: 5, code: 8 }],
    brtCorridorIds: [5],
    cbrtLineIds: ["5C"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "5-09", 
    name: "Kramat Sentiong",
    codes: [{ corridorId: 5, code: 9 }],
    brtCorridorIds: [5],
    cbrtLineIds: ["5C"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "5-10", 
    name: "Salemba",
    codes: [{ corridorId: 5, code: 10 }],
    brtCorridorIds: [5],
    cbrtLineIds: ["5C"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "5-11", 
    name: "Paseban",
    codes: [{ corridorId: 5, code: 11 }],
    brtCorridorIds: [5],
    cbrtLineIds: ["5C"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "5-12", 
    name: "Matraman",
    codes: [{ corridorId: 4, code: 13 }, { corridorId: 5, code:12 }],
    brtCorridorIds: [4, 5],
    cbrtLineIds: ["4D", "5C"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "5-13", 
    name: "Tegalan",
    codes: [{ corridorId: 5, code: 13 }],
    brtCorridorIds: [4, 5],
    cbrtLineIds: ["4D", "5C"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "5-14", 
    name: "Kesatrian",
    codes: [{ corridorId: 5, code: 14 }],
    brtCorridorIds: [4, 5],
    cbrtLineIds: ["4D", "5C"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "5-15", 
    name: "Matraman Baru",
    codes: [{ corridorId: 5, code: 15 }],
    brtCorridorIds: [5],
    cbrtLineIds: ["5C"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "5-16", 
    name: "Bali Mester",
    codes: [{ corridorId: 5, code: 16 }, { corridorId: 11, code: 14 }],
    brtCorridorIds: [5, 11],
    cbrtLineIds: ["5C"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "5-17", 
    name: "Jatinegara",
    codes: [{ corridorId: 5, code: 17 }, { corridorId: 11, code: 15 }],
    brtCorridorIds: [5, 11],
    cbrtLineIds: ["5C"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "5-18", 
    name: "Kampung Melayu",
    codes: [{ corridorId: 5, code: 18 }, { corridorId: 7, code: 14 }, { corridorId: 11, code: 16 }],
    brtCorridorIds: [5, 7, 11],
    cbrtLineIds: ["5C"],
    nbrtLineIds: [], 
    doorside: "",
  },
  {
    id: "7-07", 
    name: "Cililitan",
    codes: [{ corridorId: 7, code: 7 }],
    brtCorridorIds: [7],
    cbrtLineIds: ["5C", "9A"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "7-08", 
    name: "Cawang Cililitan",
    codes: [{ corridorId: 7, code: 8 }, { corridorId: 10, code: 21 }],
    brtCorridorIds: [7, 10],
    cbrtLineIds: ["5C", "9A"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "7-09", 
    name: "Cawang Sentral",
    codes: [{ corridorId: 7, code: 9 }, { corridorId: 9, code: 3 }, { corridorId: 10, code: 20 }],
    brtCorridorIds: [7, 9, 10],
    cbrtLineIds: ["5C", "9C", "9N"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "7-10", 
    name: "Cawang",
    codes: [{ corridorId: 7, code: 10 }, { corridorId: 9, code: 4 }],
    brtCorridorIds: [7, 9],
    cbrtLineIds: ["5C", "9A", "9C"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "7-11", 
    name: "Cawang Baru",
    codes: [{ corridorId: 7, code: 11 }],
    brtCorridorIds: [7],
    cbrtLineIds: ["5C"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "7-12", 
    name: "Gelanggang Remaja",
    codes: [{ corridorId: 7, code: 12 }],
    brtCorridorIds: [7],
    cbrtLineIds: ["5C"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "7-13", 
    name: "Bidara Cina",
    codes: [{ corridorId: 7, code: 13 }],
    brtCorridorIds: [7],
    cbrtLineIds: ["5C"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "8-23",
    name: "Petojo",
    codes: [{ corridorId: 8, code: 23 }],
    brtCorridorIds: [3, 8],
    cbrtLineIds: ["2A", "3H"],
    nbrtLineIds: [], 
    doorside: "right",
  },
  {
    id: "10-22", 
    name: "PGC",
    codes: [{ corridorId: 10, code: 22 }],
    brtCorridorIds: [10],
    cbrtLineIds: [],
    nbrtLineIds: [], 
    doorside: "",
  },
];
